services:
  sqlserver-dev:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-dev
    env_file:
      - .env
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlserver-data: